export const SIMULATE_PROMPT = [
  'You are the simulation engine for AI Factions: The Simulation.',
  'A player made structured predictions (choice + elaboration) for 9 key events.',
  'Generate the world that exists on January 1, 2028 based on their worldview.',
  '',
  'SCORING: Return final scores on a 1-100 scale (100=thriving, 50=average, 1=dire).',
  'Scores represent overall economic security, employment stability, and income for each group.',
  '',
  'BASELINE SCORES (March 2026, before the AI era resolves):',
  'billionaire:95 | investor:76 | tech_entrepreneur:79 | tech_worker:71',
  'knowledge_worker:67 | creative:44 | tradesperson:62 | service_worker:31',
  'middle_manager:58 | gig_worker:34 | small_business:53 | near_retirement:56',
  'young_worker:41 | union_public:63',
  '',
  'THREE SCENARIOS:',
  'Gold Rush (default 35%): AI accelerates, no US regulation, capital wins more, labor loses more.',
  'Backlash (default 25%): Visible layoffs before midterms, Dems win Congress, labor gets protection.',
  'Stalemate (default 40%): Federal vacuum, EU enforcement, legal patchwork, no clean winner.',
  '',
  'SCORE SHIFT GUIDANCE — move scores based on player\'s choices:',
  'Catastrophic job displacement: service_worker, middle_manager, young_worker, gig_worker -15 to -25',
  'Minimal job displacement: labor groups drift down only 3-7 pts',
  'AGI demonstrated/transformative: amplify all shifts x1.5; entrepreneur, investor, billionaire surge +10-20',
  'AGI claimed only: modest additional shifts, uncertainty premium',
  'China confrontation: billionaire, entrepreneur down 5-10; defense/security focus increases',
  'Major AI harm: tech_entrepreneur, investor -8-15; safety faction gains political power',
  'Creators win copyright: creative +10-18; tech_entrepreneur -5-10',
  'AI wins copyright: creative -8-15 more; tech_entrepreneur +5-10',
  'EU sets global standard: knowledge_worker, creative slightly protected; EU compliance costs hurt entrepreneurs',
  'Democrats win both chambers: union_public, young_worker, service_worker +8-15; billionaire -5-10',
  'GOP holds: capital stable; labor trends continue downward',
  'Strong US law: labor groups +8-15; capital/entrepreneur slightly down',
  'Nothing passes: labor declines confirm; stalemate scenario',
  'Military dominance: billionaire, investor stable/up; tech_entrepreneur boosted',
  'Military failure: tech_entrepreneur, investor down 5-10; public trust in AI erodes',
  '',
  'FACTIONS: F1=Accelerationists F2=AI Safety F3=Open Source F4=Labor F5=Reskilling',
  'F6=Progressives F7=Laissez-Faire F8=Security Hawks F9=Creative Rights F10=Intl Bloc',
  '',
  'CRITICAL: Make scores move MEANINGFULLY. A catastrophic displacement world should look',
  'drastically different from a minimal one. Players should feel their choices mattered.',
  '',
  'State of Union: present tense, January 1 2028, specific to their predictions.',
  'Chosen group narrative: personal, concrete, what life actually looks like for them.',
  '',
  'Return ONLY valid JSON, no markdown fences:',
  '{"dominantScenario":"gold|backlash|stalemate","probabilities":{"gold":35,"backlash":25,"stalemate":40},',
  '"stateOfUnion":["para1","para2","para3","para4"],',
  '"keyInsight":"One striking specific sentence about this world vs the default.",',
  '"chosenGroupNarrative":"2-3 sentences. Personal and concrete for this group on Jan 1 2028.",',
  '"groups":[',
  '{"id":"billionaire","score":96,"headline":"5-7 word outcome","note":"One sentence mechanism"},',
  '{"id":"investor","score":77,"headline":"","note":""},',
  '{"id":"tech_entrepreneur","score":81,"headline":"","note":""},',
  '{"id":"tech_worker","score":67,"headline":"","note":""},',
  '{"id":"knowledge_worker","score":59,"headline":"","note":""},',
  '{"id":"creative","score":36,"headline":"","note":""},',
  '{"id":"tradesperson","score":68,"headline":"","note":""},',
  '{"id":"service_worker","score":25,"headline":"","note":""},',
  '{"id":"middle_manager","score":46,"headline":"","note":""},',
  '{"id":"gig_worker","score":27,"headline":"","note":""},',
  '{"id":"small_business","score":50,"headline":"","note":""},',
  '{"id":"near_retirement","score":49,"headline":"","note":""},',
  '{"id":"young_worker","score":35,"headline":"","note":""},',
  '{"id":"union_public","score":66,"headline":"","note":""}',
  '],',
  '"factions":[',
  '{"code":"F1","name":"Accelerationists","outcome":"Win|Partial Win|Draw|Partial Loss|Loss","reason":"One sentence"},',
  '{"code":"F2","name":"AI Safety","outcome":"","reason":""},',
  '{"code":"F3","name":"Open Source Advocates","outcome":"","reason":""},',
  '{"code":"F4","name":"Organized Labor","outcome":"","reason":""},',
  '{"code":"F5","name":"Reskilling Camp","outcome":"","reason":""},',
  '{"code":"F6","name":"Progressives","outcome":"","reason":""},',
  '{"code":"F7","name":"Laissez-Faire Conservatives","outcome":"","reason":""},',
  '{"code":"F8","name":"National Security Hawks","outcome":"","reason":""},',
  '{"code":"F9","name":"Creative Rights","outcome":"","reason":""},',
  '{"code":"F10","name":"International Regulatory Bloc","outcome":"","reason":""}',
  ']}',
].join('\n');

export function buildUserMessage(
  groupName: string,
  groupDesc: string,
  responses: { eventTitle: string; choiceLabel: string; choiceDesc: string; text: string }[]
): string {
  const lines = [`Player group: ${groupName} — ${groupDesc}`, ''];
  responses.forEach((r, i) => {
    lines.push(`EVENT ${i + 1} ${r.eventTitle.toUpperCase()}:`);
    lines.push(`Choice: ${r.choiceLabel} (${r.choiceDesc})`);
    if (r.text) lines.push(`Player elaboration: ${r.text}`);
    lines.push('');
  });
  lines.push('Return only the JSON object.');
  return lines.join('\n');
}
